apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service-canary
  labels:
    app: pricing-canary
    canary: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricing-canary
  template:
    metadata:
      labels:
        app: pricing-canary
        canary: "true"
    spec:
      serviceAccountName: pricing-service-sa
      containers:
        - name: pricing-consumer-canary
          # This image name matches the key in imagedefinitions.json
          image: 497588665354.dkr.ecr.us-east-1.amazonaws.com/ecomm/pricing-service:latest
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"